In [25]:
import pandas as pd

In [26]:
tabela = pd.read_csv('projekt_tabela.csv', index_col='id')

In [27]:
podatki1 = pd.read_csv('projekt_podatki1.csv', index_col='predznak')

In [28]:
podatki2 = pd.read_csv('projekt_podatki2.csv', index_col='predznak')

In [29]:
tabela

,tema,stevilo_komentarjev,stevilo_ocen_komentarjev,stevilo_pozitivnih,stevilo_negativnih,ocena_novice,stevilo_ocen
id,,,,,,,
386465,zabava,18,45,33,12,1.0,9
385917,zabava,14,23,16,7,3.7,13
386457,zabava,12,13,7,6,1.7,9
386450,zabava,170,780,651,129,2.7,42
386434,zabava,32,214,111,103,3.0,21
386428,zabava,4,1,1,0,4.3,13
386417,zabava,0,0,0,0,1.0,1
386412,zabava,16,24,23,1,3.2,8
385912,zabava,50,231,167,64,2.4,18
386383,zabava,20,27,21,6,3.4,8
386398,zabava,4,15,13,2,3.0,6
386397,zabava,24,60,55,5,1.7,18
386390,zabava,12,9,2,7,2.0,4
386384,zabava,12,15,4,11,1.3,6
386380,zabava,38,237,216,21,1.5,17
386375,zabava,12,33,26,7,2.0,4
386361,zabava,20,32,23,9,5.0,4
386356,zabava,2,0,0,0,4.7,3
386351,zabava,0,0,0,0,4.0,1
386345,zabava,96,532,307,225,3.2,40
386435,zabava,0,0,0,0,2.0,35
386438,zabava,50,169,136,33,2.1,20
386381,zabava,312,1998,1497,501,3.9,63
386345,zabava,96,532,307,225,3.2,40
386277,zabava,62,394,241,153,4.7,42
385738,zabava,0,0,0,0,-1.0,0
386476,sport,18,10,9,1,5.0,1
386470,sport,58,364,277,87,4.4,16
386468,sport,6,3,3,0,3.7,3
386463,sport,10,10,8,2,5.0,1
...,...,...,...,...,...,...,...
386362,novice,348,2564,1940,624,-1.0,0
386407,novice,234,1096,818,278,-1.0,0
386475,novice,6,8,8,0,-1.0,0
386424,novice,120,671,394,277,-1.0,0
386407,novice,234,1097,819,278,-1.0,0
386445,novice,38,99,67,32,-1.0,0
386377,novice,120,431,328,103,-1.0,0
386287,novice,190,1238,890,348,-1.0,0
386323,novice,58,170,105,65,-1.0,0
386277,novice,62,394,241,153,-1.0,0
386275,novice,24,118,118,0,-1.0,0
386220,novice,238,1438,1072,366,-1.0,0
386452,novice,2,0,0,0,-1.0,0
386458,novice,8,10,9,1,-1.0,0
385738,novice,0,0,0,0,-1.0,0
386071,novice,4,0,0,0,-1.0,0
386416,novice,0,0,0,0,-1.0,0
386414,novice,0,0,0,0,-1.0,0
386411,novice,0,0,0,0,-1.0,0
386167,novice,0,0,0,0,-1.0,0
386452,novice,2,0,0,0,-1.0,0
386461,novice,2,0,0,0,-1.0,0
386258,novice,56,446,313,133,-1.0,0
386197,novice,138,1510,1056,454,-1.0,0
386438,novice,50,169,136,33,-1.0,0
386381,novice,312,1998,1497,501,-1.0,0
386345,novice,96,532,307,225,-1.0,0
386277,novice,62,394,241,153,-1.0,0
385738,novice,0,0,0,0,-1.0,0
386283,novice,0,0,0,0,-1.0,0

In [30]:
podatki1

                   sport  novice  kultura  zabava  tureavanture
predznak
vseh_komentarjev    2410    4166      636    1076          1520
pozitivninih_ocen   8093   19013     2351    3857          6479
negativninih_ocen   3209    8036      971    1527          2339

In [31]:
podatki2

                    stevilo
predznak
vseh_komentarjev       9808
pozitivnivnih_ocen    39793
negativninih_ocen     16082

In [32]:
tabela.groupby('tema').size()

tema
kultura         27
novice          50
sport           26
tureavanture    26
zabava          26
dtype: int64

In [33]:
tabela.groupby('tema').mean()

,stevilo_komentarjev,stevilo_ocen_komentarjev,stevilo_pozitivnih,stevilo_negativnih,ocena_novice,stevilo_ocen
tema,,,,,,
kultura,23.555556,123.037037,87.074074,35.962963,3.203704,12.222222
novice,83.320000,540.980000,380.260000,160.720000,-1.000000,0.000000
sport,92.692308,434.692308,311.269231,123.423077,3.665385,18.076923
tureavanture,58.461538,339.153846,249.192308,89.961538,3.538462,26.538462
zabava,41.384615,207.076923,148.346154,58.730769,2.680769,17.115385